### ISSUE TITLE
Unable to update workspace dependencies

### ISSUE THREAD

**Issue by BenJeau** [BenJeau/cargo-interactive-update#1]
The updating mechanism `cargo add ...` doesn't support modifying workspace dependencies - https://github.com/rust-lang/cargo/issues/10608

Consider maybe instead modifying directly the `Cargo.toml` file then running `cargo check`

**Comment by dessalines** [comment]
This should be re-opened, as I've found this won't update your workspace projects own `Cargo.toml` files. This currently only works for the top-level one.

**Comment by BenJeau** [comment]
Hi @dessalines!

I think what you are describing is just a feature that this CLI tool doesn't support currently. The bug related to this issue was maybe not clear enough, but was about updating the `[workspace.dependencies]` section within the `Cargo.toml` file, which `cargo add ...` doesn't support (which was what this was using initially).

For you use-case, although it is not the best but should work, you could run the tool in every folder where there's a `Cargo.toml` where you want to update the dependencies. At the moment, the tool only looks and updates the `Cargo.toml` file at the current working directory.

Let me know if I understand your comment :)

**Comment by BenJeau** [comment]
Created a new issue https://github.com/BenJeau/cargo-interactive-update/issues/10 regarding updating deps of `Cargo.toml` files of workspaces.

**Comment by dessalines** [comment]
> I think what you are describing is just a feature that this CLI tool doesn't support currently. 

Ah yep you're correct, thx for opening up a new issue. I'll comment there.
